# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup .NET 7
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 7.x
      - name: Setup .NET workload android
        run: dotnet workload install android
      - name: Setup .NET workload wasm-tools
        run: dotnet workload install wasm-tools
      - name: Update relative paths
        working-directory: src/WebConverter/wwwroot
        run: |
            sed -i 's/<base href="\/" \/>/<base href="\/${{github.event.repository.name}}\/" \/>/g' index.html
            sed -i 's/"scope": "\/"/"scope": "\/${{github.event.repository.name}}\/"/g' manifest.webmanifest
            sed -i 's/"start_url": "\/"/"start_url": "\/${{github.event.repository.name}}\/"/g' manifest.webmanifest
            sed -i 's/"action": "\/"/"action": "\/${{github.event.repository.name}}\/"/g' manifest.webmanifest
            sed -i 's/"action": "\/receive-webshare"/"action": "\/${{github.event.repository.name}}\/receive-webshare"/g' manifest.webmanifest
            sed -i "s/return Response.redirect\(\'\/\', 303\);/return Response.redirect\(\'\/${{github.event.repository.name}}\/\', 303\);/g" service-worker.published.js
      - name: Restore
        run: dotnet restore src/PDFtoImage.sln
      - name: Publish
        run: dotnet publish src/WebConverter/WebConverter.csproj -c Release -p:PublishProfile=src/WebConverter/Properties/PublishProfiles/PublishSite.pubxml --no-restore
      - name: Create .nojekyll file
        run: touch src/WebConverter/bin/Release/net7.0/publish/wwwroot/.nojekyll
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: src/WebConverter/bin/Release/net7.0/publish/wwwroot
  deploy:
    name: Deploy
    needs: publish
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
